language: java
dist: trusty
jdk:
  - openjdk8
addons:
  apt:
    update: true
before_install:
  - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip
  - mkdir /opt/gradle
  - unzip -d /opt/gradle gradle-5.0-bin.zip
  - export GRADLE=/opt/gradle/gradle-5.0/bin/gradle
install: true
script: ./travis.sh
