language: java
dist: trusty
jdk:
  - openjdk8
addons:
  apt:
    update: true
before_install:
  - curl https://gradle.org/next-steps/?version=5.0&format=bin
  - mkdir /opt/gradle
  - unzip -d /opt/gradle gradle-5.0-bin.zip
  - export GRADLE=/opt/gradle/gradle-5.0/bin/gradle
install: true
script: ./travis.sh
